s = set()

a =input("Enter Nymber : ")
s.add(int(a))
a =input("Enter Nymber : ")
s.add(int(a))
a =input("Enter Nymber : ")
s.add(int(a))
a =input("Enter Nymber : ")
s.add(int(a))
a =input("Enter Nymber : ")
s.add(int(a))
a =input("Enter Nymber : ")
s.add(int(a))
a =input("Enter Nymber : ")
s.add(int(a))
a =input("Enter Nymber : ")
s.add(int(a))

print(s)